/**:
  ros__parameters:
    gripper_type: "2FG7"
    ip_address: "192.168.1.1"  # Default IP address
    port: 502
    max_width: 0.085
    min_width: 0.0
    max_force: 100.0
    update_rate: 100.0
    use_sim_time: false