/**:
  ros__parameters:
    gripper_type: "2FG7"
    ip_address: "192.168.1.1"
    port: 502
    max_width: 0.075    # 75mm max opening
    min_width: 0.035    # 35mm min opening
    max_force: 100.0
    update_rate: 100.0
    simulation_mode: false