# OnRobot Gripper ROS2 Parameters
# This YAML file configures the OnRobot gripper driver node.
# Adjust these parameters to match your hardware setup and requirements.

/**:
  ros__parameters:
    # Gripper model type (e.g., "2FG7", "2FG14", etc.)
    gripper_type: "2FG7"

    # IP address of the OnRobot Compute Box (default from documentation)
    ip_address: "192.168.1.1"

    # TCP port for communication (default Modbus TCP port is 502)
    port: 502

    # Device address based on mounting option (from documentation)
    device_address: 65  # 65 for Quick Changer, 66/67 for Dual Quick Changer

    # Maximum opening width of the gripper in meters (adjust for your gripper model)
    max_width: 0.070    # 70mm max opening for 2FG7

    # Minimum opening width of the gripper in meters (adjust for your gripper model)
    min_width: 0.035    # 35mm min opening for 2FG7

    # Maximum gripping force in Newtons
    max_force: 100.0

    # Default speed percentage (10-100%)
    default_speed: 50

    # Default grip mode ("external" or "internal")
    default_grip_mode: "external"

    # Driver update rate in Hz (how often to poll and command the gripper)
    update_rate: 100.0

    # Enable simulation mode (true = no hardware required, for testing)
    simulation_mode: false

    # Joint name for the gripper
    joint_name: "left_finger_joint"

    # Command timeout in seconds
    command_timeout: 10.0