# OnRobot Gripper ROS2 Simulation Parameters
# This YAML file configures the OnRobot gripper driver node for simulation.
# Adjust these parameters for your simulation environment.

/**:
  ros__parameters:
    # Gripper model type (e.g., "2FG7", "2FG14", etc.)
    gripper_type: "2FG7"

    # IP address for simulation (localhost)
    ip_address: "127.0.0.1"

    # TCP port for simulation (use a non-standard port to avoid conflicts)
    port: 1502

    # Device address for simulation
    device_address: 65

    # Maximum opening width of the gripper in meters (e.g., 0.070 = 70mm)
    max_width: 0.070    # 70mm max opening

    # Minimum opening width of the gripper in meters (e.g., 0.035 = 35mm)
    min_width: 0.035    # 35mm min opening

    # Maximum gripping force in Newtons
    max_force: 100.0

    # Driver update rate in Hz (lower for simulation)
    update_rate: 10.0

    # Enable simulation mode (true = no hardware required)
    simulation_mode: true

    # Joint name for the gripper
    joint_name: "left_finger_joint"

    # Command timeout in seconds
    command_timeout: 10.0