/**:
  ros__parameters:
    gripper_type: "2FG7"
    ip_address: "127.0.0.1"  # Use localhost for testing
    port: 1502               # Use non-privileged port for mock server
    max_width: 0.085
    min_width: 0.0
    max_force: 100.0
    update_rate: 10.0        # Lower rate for testing
    use_sim_time: false